# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

require 'messages_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module ProtobufRubyExample
  module Proto
  end
end
