# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'ProtobufRubyExample.Proto'

require 'grpc'
require 'api_pb'

module ProtobufRubyExample
  module Proto
    module Api
      # An RPC service for ProtobufRubyExample.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ProtobufRubyExample.Proto.Api'

        # A sample RPC method
        #
        # Accepts a RequestPb.
        # Returns a ResponsePb.
        rpc :SomeMethod, RequestPb, ResponsePb
      end

      Stub = Service.rpc_stub_class
    end
  end
end
