# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ProtobufRubyExample.Proto.RequestPb" do
    optional :id, :int64, 1
    optional :message, :string, 2
  end
  add_message "ProtobufRubyExample.Proto.ResponsePb" do
    optional :id, :int64, 1
    optional :status, :string, 2
  end
end

module ProtobufRubyExample
  module Proto
    RequestPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtobufRubyExample.Proto.RequestPb").msgclass
    ResponsePb = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtobufRubyExample.Proto.ResponsePb").msgclass
  end
end
